### ISSUE TITLE
Кнопки зума не работают

### ISSUE THREAD

**Issue by linpus** [egaxegax/dbcartajs#2]
Отличная библиотека! Но есть баг.
Кнопки зума работают только если позиция контейнера начинается с левого верхнего угла экрана.

Вот так работает (контейнер на весь экран):
`<div id="mcont" style="width:100%; height:100%; border:1px solid gray;">`

Если сдвинуть контейнер в середину экрана и задать меньшие размеры то не работает:
`<div id="mcont" style="width:50%; height:50%; margin: 0 auto; border:1px solid gray;">`

Причем если кликать гдето в середине контейнера то зум срабатывает, а на кнопках - нет. Видимо смещаются координаты клика, примерно на разницу начала экрана и начала контейнера.

Зум колесиком и панорама работают как обычно.

**Comment by linpus** [comment]
Нашел где поправить, но не уверен что это невызовет баг гдето в другом месте.
Поменял client на offset
```
canvasXY: function(ev) {
      var node = cont,
          //pts = [ev.clientX, ev.clientY];
          pts = [ev.offsetX, ev.offsetY];
      if (!/WebKit/.test(navigator.userAgent)) {
        pts[0] += window.pageXOffset;
        pts[1] += window.pageYOffset;
      }
      while (node) {
         pts[0] -= node.offsetLeft - node.scrollLeft;
         pts[1] -= node.offsetTop - node.scrollTop;
         node = node.offsetParent;
      }
      return pts;
    },
```

**Comment by egaxegax** [comment]
Ошибка скорее всего в функции **chkBar**. Она вычисляет позицию клика (события mousedown, mouseup) на скейлбаре. Но я ошибку не смог повторить. Сбросьте полный пример скрипта и напишите в каком браузере не работает. Спасибо за отзыв.

**Comment by linpus** [comment]
```
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>html,body {overflow:hidden;margin:0;padding:0;width:100%;height:100%}</style>
</head>
<body>

<!-- так работает-->
<!--<div id="mcont" style="width:100%; height:100%; border:1px solid gray;">-->

<!-- так не работает-->
<div id="mcont" style="width:50%; height:50%; margin: 0 auto; border:1px solid gray;">

  <svg xmlns="http://www.w3.org/2000/svg" width="0" height="0">
    <g id="viewport" fill="none">
      <rect style="fill:#ac9d93" width="600" height="600" x="0"  y="0" />
      <ellipse style="fill:#00ffff" cx="300" cy="300" rx="50" ry="50" />
    </g>
  </svg>
</div>

<script src="../js/dbcartasvg.js"></script>
<script>
[].slice.call(document.getElementsByTagName('svg')).map(function(o){
  var root = o,
      vp = document.getElementById('viewport');
  var old_width = vp.getBoundingClientRect().right - vp.getBoundingClientRect().left,
      old_height = vp.getBoundingClientRect().bottom - vp.getBoundingClientRect().top;
  var new_width = document.getElementById('mcont').offsetWidth,
      new_height = document.getElementById('mcont').offsetHeight;
  var DC = new dbCartaSvg({
    svgRoot: root,
    svgViewport: vp,
    width: new_width,
    height: new_height
  });
  DC.vp.style.cursor = 'pointer';
  DC.centerCarta([ old_width/2, old_height/2 ]);
  DC.scaleCarta( new_height / old_height );
});

</script>
</body>
</html>
```
Firefox 125.0.3
Yandex Browser 24.4.1.915

**Comment by egaxegax** [comment]
Поправил ошибку. Она Действительно была в функции canvasXY - элемент cont был неопределен (undefined). В своем примере [panzoom.html](https://egaxegax.github.io/dbcartajs/svg/panzoom.html) сместил тигра в центр как в твоем случае чтобы протеститровать этот вариант.
PS. Поставь звездочку проекту тебе будет не сложно, а мне очень приятно. Спасибо за участие

**Comment by egaxegax** [comment]
Поправил ошибку. Она Действительно была в функции canvasXY - элемент cont был неопределен (undefined). В своем примере [panzoom.html](https://egaxegax.github.io/dbcartajs/svg/panzoom.html) сместил тигра в центр как в твоем случае чтобы протеститровать этот вариант.
PS. Поставь звездочку проекту тебе будет не сложно, а мне очень приятно. Спасибо за участие
