### ISSUE TITLE
баннеры

### ISSUE THREAD

**Issue by KarelWintersky** [egaxegax/dbcartajs#3]
Это нормально, что egaxegax.github.io обвешан баннерами по самое неуподоблюсь?

**Comment by egaxegax** [comment]
Это просто реклама от Яндекс, как и на многих других сайтах, которую я подключил. Один-два баннера на странице - не много. Я экспериментирую и меняю часто размеры и количество блоков нас сайте. Пока не добился оптимальности,  меня тоже не всё устаривает, но убирать совсем не буду.

**Comment by KarelWintersky** [comment]
Один-два? Вы на сайте-то давно были? 

И как, денег много приносит?

**Comment by egaxegax** [comment]
В прошлом году (с августа 23-го) удавалось что-то заработать ~ 1000-1200 руб в месяц при 100-150 посетителях в сутки. В этом году (с апреля) сайт перевел на новый домен egax.ru вместо egaxegax.github.io (в гитхабе есть возможность подключить свой домен), посещаемость сейчас упала до 10-20 чел/сут, ставки на рекламу упали с 200-1000 руб до 20-40 руб за 1000 показов в итоге доход за день < 10 руб, т.е. почти ничего. Я и не планировал особо зарабатывать просто изучаю инструменты монетизации. К сайту у меня также подключена ещё и VK реклама, но она не показывается (веб-сервер гигхаба не шлет куки,а рекламному серверу они нужны, как сказали в тех.поддержке ВК). Поэтому я и поменял домен и дальше и сайт хочу перенести на платный хостинг (где можно настраивать окружение, веб-сервер и т.п) с бестплатного гитхабоского GitHub Pages. [KarelWintersky](https://github.com/KarelWintersky) у тебя тоже есть сайт [https://karel.wintersky.ru/](https://karel.wintersky.ru/). Зарегистрируйся в РСЯ (Яндекс Рекламе) создай 1 блок и размести код у себя и сам всё увидишь через некоторое время. Только на сайте у тебя 1 работающая страница, создать хотя бы 10 не битых и всё.

**Comment by KarelWintersky** [comment]
Я не буду этого делать. По трем причинам.

1. Я работаю в интернет-СМИ и ненавижу баннеры всей душой. 
2. Мой сайт никто не посещает (а еще у меня нет ни малейшего желания его вести и разрабатывать, основная моя активность в телеграме), 
3. Те хобби-пет-проекты, которые у меня есть - идут без баннеров. Потому что я понимаю, что если пользователь придёт на тот же https://storymaps.ru/ и увидит там стопицот баннеров - он с омерзением его закроет. Оно мне надо?

Почему я вообще увидел баннеры, а их не порезала баннеррезка. См пункт 1., я должен видеть разрабатываемый сайт в том виде, в котором его увидит большинство пользователей. Да, с баннерами.

**Comment by KarelWintersky** [comment]
Но ваши аргументы я услышал. Спасибо, что объяснили. Дело ваше, конечно. Просто учитывайте реакцию посетителей.
